platform :ios, '9.0'

target 'RNTypescriptDemo' do 
  # Pods for RNTypescriptDemo
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTNetwork',
      'RCTVibration',
      'RCTSettings',
      'RCTAnimation',
      'RCTLinkingIOS',
      'RCTImage',
  ]
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

target 'RNTypescriptDemoTests' do
    inherit! :search_paths
    # Pods for testing
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        # The following is needed to ensure the "archive" step works in XCode.
        # It removes React & Yoga from the Pods project, as it is already included in the main project.
        # Without this, you'd see errors when you archive like:
        # "Multiple commands produce ... libReact.a"
        # "Multiple commands produce ... libyoga.a"
        
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
        
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
        
    end
end
